"""add geofencing and attendance source

Revision ID: 4118e0a19b17
Revises: a1b2c3d4e5f7
Create Date: 2026-03-10 17:31:20.015066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4118e0a19b17'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('source', sa.String(length=20), server_default=sa.text("'k40_device'"), nullable=False, comment='k40_device or mobile_app'))
    op.alter_column('attendance_records', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_attendance_records_source'), 'attendance_records', ['source'], unique=False)
    op.add_column('schools', sa.Column('geofence_lat', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('geofence_lng', sa.Float(), nullable=True))
    op.add_column('schools', sa.Column('geofence_radius_m', sa.Integer(), nullable=True))
    op.alter_column('schools', 'school_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # VARCHAR -> JSON: convert existing single subject string to one-element array
    op.execute("""
        ALTER TABLE teachers ALTER COLUMN subject TYPE JSON
        USING (CASE WHEN subject IS NULL OR trim(subject) = '' THEN NULL ELSE json_build_array(subject) END)
    """)
    op.execute("COMMENT ON COLUMN teachers.subject IS 'List of subjects taught'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'subject',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=150),
               comment='Primary subject taught',
               existing_comment='List of subjects taught',
               existing_nullable=True)
    op.alter_column('schools', 'school_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'mixed'::character varying"),
               existing_nullable=False)
    op.drop_column('schools', 'geofence_radius_m')
    op.drop_column('schools', 'geofence_lng')
    op.drop_column('schools', 'geofence_lat')
    op.drop_index(op.f('ix_attendance_records_source'), table_name='attendance_records')
    op.alter_column('attendance_records', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('attendance_records', 'source')
    # ### end Alembic commands ###

