"""add teacher_id to attendance_records

Revision ID: 8aae4eadf9a7
Revises: bceb93335a7a
Create Date: 2026-02-20 00:35:03.280221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aae4eadf9a7'
down_revision: Union[str, None] = 'bceb93335a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attendance_records_teacher_id'), 'attendance_records', ['teacher_id'], unique=False)
    op.create_foreign_key(None, 'attendance_records', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendance_records', type_='foreignkey')
    op.drop_index(op.f('ix_attendance_records_teacher_id'), table_name='attendance_records')
    op.drop_column('attendance_records', 'teacher_id')
    # ### end Alembic commands ###

