"""add is_boarding to students

Revision ID: d6bc063654ab
Revises: 27f8bcf26c9c
Create Date: 2026-02-20 00:12:26.708092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6bc063654ab'
down_revision: Union[str, None] = '27f8bcf26c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reporter_name', sa.String(length=200), nullable=True),
    sa.Column('reporter_email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_access_token'), 'support_tickets', ['access_token'], unique=True)
    op.create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_support_tickets_reporter_email'), 'support_tickets', ['reporter_email'], unique=False)
    op.create_index(op.f('ix_support_tickets_school_id'), 'support_tickets', ['school_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_support_tickets_user_id'), 'support_tickets', ['user_id'], unique=False)
    op.create_table('ticket_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=200), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('is_admin_reply', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_messages_id'), 'ticket_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_messages_ticket_id'), 'ticket_messages', ['ticket_id'], unique=False)
    op.add_column('students', sa.Column('is_boarding', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_students_is_boarding'), 'students', ['is_boarding'], unique=False)
    op.alter_column('teachers', 'subject',
               existing_type=sa.VARCHAR(length=150),
               comment='Primary subject taught',
               existing_nullable=True)
    op.alter_column('teachers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_constraint('uq_teachers_school_phone', 'teachers', type_='unique')
    op.create_table_comment(
        'teachers',
        'Teachers registered in schools — each has a unique phone per school',
        existing_comment='Teachers registered in schools',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'teachers',
        'Teachers registered in schools',
        existing_comment='Teachers registered in schools — each has a unique phone per school',
        schema=None
    )
    op.create_unique_constraint('uq_teachers_school_phone', 'teachers', ['school_id', 'phone'])
    op.alter_column('teachers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=True)
    op.alter_column('teachers', 'subject',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment='Primary subject taught',
               existing_nullable=True)
    op.drop_index(op.f('ix_students_is_boarding'), table_name='students')
    op.drop_column('students', 'is_boarding')
    op.drop_index(op.f('ix_ticket_messages_ticket_id'), table_name='ticket_messages')
    op.drop_index(op.f('ix_ticket_messages_id'), table_name='ticket_messages')
    op.drop_table('ticket_messages')
    op.drop_index(op.f('ix_support_tickets_user_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_school_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_reporter_email'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_access_token'), table_name='support_tickets')
    op.drop_table('support_tickets')
    # ### end Alembic commands ###

